import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./_styles/globals.scss"
import localFont from 'next/font/local'
import { TemplateProvider } from "./_libs/providers/CustomThemeProvider";
import { ReduxProvider } from "./_libs/providers/ReduxProvider";
import { AuthProvider } from "./_libs/providers/AuthContext";

// Add fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Local font
// const myFont = localFont({
//   src: './my-font.woff2',
// })

// Add metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReduxProvider>
          <AuthProvider>
            <TemplateProvider>
              <ReduxProvider>
                {children}
              </ReduxProvider>
            </TemplateProvider>
          </AuthProvider>
        </ReduxProvider>

      </body>
    </html>
  );
}
