import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import "../../styles/globals.scss";
import { TemplateProvider } from "../../context/CustomThemeProvider";
import { ReduxProvider } from "../../context/ReduxProvider";
import { AuthProvider } from "../../context/AuthContext";
import { NextIntlClientProvider, hasLocale } from "next-intl";
import { notFound } from "next/navigation";
import { routing } from "../../i18n/routing";
import { setRequestLocale } from "next-intl/server";

// import { Inter } from "next/font/google";
// const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

// // Add fonts
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// Local font
// const myFont = localFont({
//   src: './my-font.woff2',
// })

// Add metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface Props {
  children: React.ReactNode;
  params: { locale: string };
}

export const dynamicParams = true; // Cho phép dynamic routes

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export default async function RootLayout({ children, params }: Props) {
  const { locale } = await params;
  console.log("Layout", locale);
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  // Enable static rendering
  setRequestLocale(locale);

  const messages = (await import(`../../i18n/message/${locale}.json`)).default;

  return (
    <html lang="en">
      <body className={`antialiased bg-white text-black font-sans`}>
        <ReduxProvider>
          <AuthProvider>
            <TemplateProvider>
              <NextIntlClientProvider locale={locale} messages={messages}>
                {children}
              </NextIntlClientProvider>
            </TemplateProvider>
          </AuthProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
